package br.com.fiap.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2016-10-20T11:51:34.844-02:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://endpoint.fiap.com.br/", name = "EndpointFinanceiro")
@XmlSeeAlso({ObjectFactory.class})
public interface EndpointFinanceiro {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "cobrarMensalidadeResponse", targetNamespace = "http://endpoint.fiap.com.br/", partName = "result")
    @WebMethod
    public CobrarMensalidadeResponse cobrarMensalidade(
        @WebParam(partName = "parameters", name = "cobrarMensalidade", targetNamespace = "http://endpoint.fiap.com.br/")
        CobrarMensalidade parameters,
        @WebParam(partName = "username", name = "username", targetNamespace = "http://endpoint.fiap.com.br/", header = true)
        java.lang.String username,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://endpoint.fiap.com.br/", header = true)
        java.lang.String password
    ) throws Exception_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "saldoResponse", targetNamespace = "http://endpoint.fiap.com.br/", partName = "parameters")
    @WebMethod
    public SaldoResponse saldo(
        @WebParam(partName = "parameters", name = "saldo", targetNamespace = "http://endpoint.fiap.com.br/")
        Saldo parameters,
        @WebParam(partName = "username", name = "username", targetNamespace = "http://endpoint.fiap.com.br/", header = true)
        java.lang.String username,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://endpoint.fiap.com.br/", header = true)
        java.lang.String password
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "cobrar", targetNamespace = "http://endpoint.fiap.com.br/", className = "br.com.fiap.endpoint.Cobrar")
    @WebMethod
    @ResponseWrapper(localName = "cobrarResponse", targetNamespace = "http://endpoint.fiap.com.br/", className = "br.com.fiap.endpoint.CobrarResponse")
    public boolean cobrar(
        @WebParam(name = "indentificador", targetNamespace = "")
        java.lang.String indentificador,
        @WebParam(name = "valor", targetNamespace = "")
        java.lang.Double valor
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "cadastrarCliente", targetNamespace = "http://endpoint.fiap.com.br/", className = "br.com.fiap.endpoint.CadastrarCliente")
    @WebMethod
    @ResponseWrapper(localName = "cadastrarClienteResponse", targetNamespace = "http://endpoint.fiap.com.br/", className = "br.com.fiap.endpoint.CadastrarClienteResponse")
    public br.com.fiap.endpoint.Cliente cadastrarCliente(
        @WebParam(name = "cliente", targetNamespace = "")
        br.com.fiap.endpoint.Cliente cliente
    ) throws Exception_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "listarClientesResponse", targetNamespace = "http://endpoint.fiap.com.br/", partName = "parameters")
    @WebMethod
    public ListarClientesResponse listarClientes(
        @WebParam(partName = "parameters", name = "listarClientes", targetNamespace = "http://endpoint.fiap.com.br/")
        ListarClientes parameters,
        @WebParam(partName = "username", name = "username", targetNamespace = "http://endpoint.fiap.com.br/", header = true)
        java.lang.String username,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://endpoint.fiap.com.br/", header = true)
        java.lang.String password
    ) throws Exception_Exception;
}
